version: '3'
services:
  proxy:
    image: webservernginx
    container_name: webserver
    build:
      context: .
    #volumes:
    #  - D:\Cloud Drive\OneDrive\Documents\GitHub\InfraII\Docker\DockerWebServer\site:/usr/share/nginx/html
    ports:
      - "8000:80"
    networks:
      - webservereth

networks: 
  webservereth:
    driver: bridge


    # docker-compose up -d