version: '3'
services:
  proxy:
    image: webserverspring
    container_name: springserver
    build:
      context: .
    #volumes:
    #  - .\site:/usr/share/nginx/htm
    #volumes:
    #  - site:/usr/share/nginx/htm
    ports:
      - "8001:8080"
    networks:
      - webserver

networks:
  webserver:
    driver: bridge

    #volumes:
    #  site:

    # docker-compose up -d